name: 'Terraform'

on:
  push:
    branches:
      - $default-branch
    paths:
      - 'stage/**'
      - 'prod/**'
  pull_request:
    paths:
      - 'stage/**'
      - 'prod/**'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.29

    - name: get paths of changed functions
      id: getpath
      run: |
        echo "::set-output name=paths::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | cut -d '/' -f1,2 | uniq | xargs)"

    - name: print paths
      run: echo ${{ steps.getpath.outputs.paths }}

    - name: Terraform Init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        for i in ${{ steps.getpath.outputs.paths }}
        do
          terraform init
        done

    - name: Terraform validate
      run: |
        for i in ${{ steps.getpath.outputs.paths }}
        do
          terraform validate
        done

    - name: Terraform format
      run: |
        for i in ${{ steps.getpath.outputs.paths }}
        do
          terraform fmt -check
        done

    - name: Terraform plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        for i in ${{ steps.getpath.outputs.paths }}
        do
          terraform plan
        done

    - name: Terraform Apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      if: github.ref == 'refs/heads/$default-branch' && github.event_name == 'push'
      run: |
        for i in ${{ steps.getpath.outputs.paths }}
        do
          terraform apply -auto-approve
        done

